package gltf

import "encoding/json"

// Index is a reference to another element in one of the Document's top-level
// arrays. glTF omits absent indices from the JSON, so it is represented as a
// pointer to an int; a nil pointer means "no reference".
type Index = int

// Document is the root object of a glTF 2.0 asset. It mirrors the JSON schema
// of the glTF specification; every top-level array is addressed by integer
// index from elsewhere in the document.
type Document struct {
	// ExtensionsUsed lists glTF extensions used somewhere in this asset.
	ExtensionsUsed []string `json:"extensionsUsed,omitempty"`
	// ExtensionsRequired lists glTF extensions required to load this asset.
	ExtensionsRequired []string `json:"extensionsRequired,omitempty"`

	Asset       Asset        `json:"asset"`
	Scene       *Index       `json:"scene,omitempty"`
	Scenes      []Scene      `json:"scenes,omitempty"`
	Nodes       []Node       `json:"nodes,omitempty"`
	Meshes      []Mesh       `json:"meshes,omitempty"`
	Accessors   []Accessor   `json:"accessors,omitempty"`
	BufferViews []BufferView `json:"bufferViews,omitempty"`
	Buffers     []Buffer     `json:"buffers,omitempty"`
	Materials   []Material   `json:"materials,omitempty"`
	Textures    []Texture    `json:"textures,omitempty"`
	Images      []Image      `json:"images,omitempty"`
	Samplers    []Sampler    `json:"samplers,omitempty"`
	Animations  []Animation  `json:"animations,omitempty"`
	Skins       []Skin       `json:"skins,omitempty"`
	Cameras     []Camera     `json:"cameras,omitempty"`

	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// Asset holds metadata about the glTF asset. The Version field is required by
// the specification.
type Asset struct {
	Copyright  string          `json:"copyright,omitempty"`
	Generator  string          `json:"generator,omitempty"`
	Version    string          `json:"version"`
	MinVersion string          `json:"minVersion,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// Scene is the root of a node hierarchy.
type Scene struct {
	Name       string          `json:"name,omitempty"`
	Nodes      []Index         `json:"nodes,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// Node is a node in the scene graph. A node may have either a Matrix or a
// combination of Translation, Rotation, and Scale, but not both.
type Node struct {
	Name        string          `json:"name,omitempty"`
	Camera      *Index          `json:"camera,omitempty"`
	Children    []Index         `json:"children,omitempty"`
	Skin        *Index          `json:"skin,omitempty"`
	Matrix      *[16]float64    `json:"matrix,omitempty"`
	Mesh        *Index          `json:"mesh,omitempty"`
	Rotation    *[4]float64     `json:"rotation,omitempty"`
	Scale       *[3]float64     `json:"scale,omitempty"`
	Translation *[3]float64     `json:"translation,omitempty"`
	Weights     []float64       `json:"weights,omitempty"`
	Extensions  json.RawMessage `json:"extensions,omitempty"`
	Extras      json.RawMessage `json:"extras,omitempty"`
}

// Mesh is a set of primitives to be rendered.
type Mesh struct {
	Name       string          `json:"name,omitempty"`
	Primitives []Primitive     `json:"primitives"`
	Weights    []float64       `json:"weights,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// Primitive describes the geometry to be rendered with a material. Attributes
// maps attribute semantics (for example "POSITION" or "NORMAL") to accessor
// indices.
type Primitive struct {
	Attributes map[string]Index   `json:"attributes"`
	Indices    *Index             `json:"indices,omitempty"`
	Material   *Index             `json:"material,omitempty"`
	Mode       *PrimitiveMode     `json:"mode,omitempty"`
	Targets    []map[string]Index `json:"targets,omitempty"`
	Extensions json.RawMessage    `json:"extensions,omitempty"`
	Extras     json.RawMessage    `json:"extras,omitempty"`
}

// GetMode returns the primitive's rendering mode, defaulting to
// PrimitiveTriangles when unset, as required by the specification.
func (p *Primitive) GetMode() PrimitiveMode {
	if p.Mode == nil {
		return PrimitiveTriangles
	}
	return *p.Mode
}

// Accessor defines how to interpret the typed data stored in a bufferView (or
// generated by a sparse substitution).
type Accessor struct {
	BufferView    *Index          `json:"bufferView,omitempty"`
	ByteOffset    int             `json:"byteOffset,omitempty"`
	ComponentType ComponentType   `json:"componentType"`
	Normalized    bool            `json:"normalized,omitempty"`
	Count         int             `json:"count"`
	Type          AccessorType    `json:"type"`
	Max           []float64       `json:"max,omitempty"`
	Min           []float64       `json:"min,omitempty"`
	Sparse        *Sparse         `json:"sparse,omitempty"`
	Name          string          `json:"name,omitempty"`
	Extensions    json.RawMessage `json:"extensions,omitempty"`
	Extras        json.RawMessage `json:"extras,omitempty"`
}

// Sparse describes displacements applied to a subset of an accessor's elements.
type Sparse struct {
	Count      int             `json:"count"`
	Indices    SparseIndices   `json:"indices"`
	Values     SparseValues    `json:"values"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// SparseIndices points to the bufferView holding the indices of the elements to
// be replaced. ComponentType must be an unsigned integer type.
type SparseIndices struct {
	BufferView    Index           `json:"bufferView"`
	ByteOffset    int             `json:"byteOffset,omitempty"`
	ComponentType ComponentType   `json:"componentType"`
	Extensions    json.RawMessage `json:"extensions,omitempty"`
	Extras        json.RawMessage `json:"extras,omitempty"`
}

// SparseValues points to the bufferView holding the replacement element values.
type SparseValues struct {
	BufferView Index           `json:"bufferView"`
	ByteOffset int             `json:"byteOffset,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// BufferView is a contiguous slice of a buffer.
type BufferView struct {
	Buffer     Index           `json:"buffer"`
	ByteOffset int             `json:"byteOffset,omitempty"`
	ByteLength int             `json:"byteLength"`
	ByteStride int             `json:"byteStride,omitempty"`
	Target     *TargetType     `json:"target,omitempty"`
	Name       string          `json:"name,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// Buffer points to binary geometry, animation, or skin data. URI may be a file
// path, a base64 data URI, or empty for the GLB binary chunk.
type Buffer struct {
	URI        string          `json:"uri,omitempty"`
	ByteLength int             `json:"byteLength"`
	Name       string          `json:"name,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`

	// Data holds the resolved bytes for this buffer once ResolveBuffers has
	// run. It is not serialized to JSON.
	Data []byte `json:"-"`
}

// Material defines the appearance of a primitive.
type Material struct {
	Name                 string                `json:"name,omitempty"`
	PBRMetallicRoughness *PBRMetallicRoughness `json:"pbrMetallicRoughness,omitempty"`
	NormalTexture        *NormalTexture        `json:"normalTexture,omitempty"`
	OcclusionTexture     *OcclusionTexture     `json:"occlusionTexture,omitempty"`
	EmissiveTexture      *TextureInfo          `json:"emissiveTexture,omitempty"`
	EmissiveFactor       *[3]float64           `json:"emissiveFactor,omitempty"`
	AlphaMode            AlphaMode             `json:"alphaMode,omitempty"`
	AlphaCutoff          *float64              `json:"alphaCutoff,omitempty"`
	DoubleSided          bool                  `json:"doubleSided,omitempty"`
	Extensions           json.RawMessage       `json:"extensions,omitempty"`
	Extras               json.RawMessage       `json:"extras,omitempty"`
}

// PBRMetallicRoughness holds the metallic-roughness material model parameters.
type PBRMetallicRoughness struct {
	BaseColorFactor          *[4]float64     `json:"baseColorFactor,omitempty"`
	BaseColorTexture         *TextureInfo    `json:"baseColorTexture,omitempty"`
	MetallicFactor           *float64        `json:"metallicFactor,omitempty"`
	RoughnessFactor          *float64        `json:"roughnessFactor,omitempty"`
	MetallicRoughnessTexture *TextureInfo    `json:"metallicRoughnessTexture,omitempty"`
	Extensions               json.RawMessage `json:"extensions,omitempty"`
	Extras                   json.RawMessage `json:"extras,omitempty"`
}

// TextureInfo references a texture and the UV set used to sample it.
type TextureInfo struct {
	Index      Index           `json:"index"`
	TexCoord   int             `json:"texCoord,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// NormalTexture references a normal map, with an additional scale factor.
type NormalTexture struct {
	Index      Index           `json:"index"`
	TexCoord   int             `json:"texCoord,omitempty"`
	Scale      *float64        `json:"scale,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// OcclusionTexture references an occlusion map, with an additional strength.
type OcclusionTexture struct {
	Index      Index           `json:"index"`
	TexCoord   int             `json:"texCoord,omitempty"`
	Strength   *float64        `json:"strength,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// Texture pairs a source image with a sampler.
type Texture struct {
	Name       string          `json:"name,omitempty"`
	Sampler    *Index          `json:"sampler,omitempty"`
	Source     *Index          `json:"source,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// Image is image data used to create a texture. Exactly one of URI or
// BufferView is expected.
type Image struct {
	Name       string          `json:"name,omitempty"`
	URI        string          `json:"uri,omitempty"`
	MimeType   string          `json:"mimeType,omitempty"`
	BufferView *Index          `json:"bufferView,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// Sampler defines texture filtering and wrapping.
type Sampler struct {
	Name       string          `json:"name,omitempty"`
	MagFilter  *Filter         `json:"magFilter,omitempty"`
	MinFilter  *Filter         `json:"minFilter,omitempty"`
	WrapS      *WrapMode       `json:"wrapS,omitempty"`
	WrapT      *WrapMode       `json:"wrapT,omitempty"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// Animation binds keyframe data (samplers) to node properties (channels).
type Animation struct {
	Name       string             `json:"name,omitempty"`
	Channels   []AnimationChannel `json:"channels"`
	Samplers   []AnimationSampler `json:"samplers"`
	Extensions json.RawMessage    `json:"extensions,omitempty"`
	Extras     json.RawMessage    `json:"extras,omitempty"`
}

// AnimationChannel connects an animation sampler to a target property.
type AnimationChannel struct {
	Sampler    Index                  `json:"sampler"`
	Target     AnimationChannelTarget `json:"target"`
	Extensions json.RawMessage        `json:"extensions,omitempty"`
	Extras     json.RawMessage        `json:"extras,omitempty"`
}

// AnimationChannelTarget identifies the node and property an animation drives.
type AnimationChannelTarget struct {
	Node       *Index          `json:"node,omitempty"`
	Path       AnimationPath   `json:"path"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}

// AnimationSampler holds keyframe input (times) and output (values) accessors.
type AnimationSampler struct {
	Input         Index           `json:"input"`
	Interpolation Interpolation   `json:"interpolation,omitempty"`
	Output        Index           `json:"output"`
	Extensions    json.RawMessage `json:"extensions,omitempty"`
	Extras        json.RawMessage `json:"extras,omitempty"`
}

// Skin defines joints and matrices for vertex skinning.
type Skin struct {
	Name                string          `json:"name,omitempty"`
	InverseBindMatrices *Index          `json:"inverseBindMatrices,omitempty"`
	Skeleton            *Index          `json:"skeleton,omitempty"`
	Joints              []Index         `json:"joints"`
	Extensions          json.RawMessage `json:"extensions,omitempty"`
	Extras              json.RawMessage `json:"extras,omitempty"`
}

// Camera is a projection used to render the scene. Exactly one of Perspective
// or Orthographic must be set, matching Type.
type Camera struct {
	Name         string              `json:"name,omitempty"`
	Type         CameraType          `json:"type"`
	Perspective  *CameraPerspective  `json:"perspective,omitempty"`
	Orthographic *CameraOrthographic `json:"orthographic,omitempty"`
	Extensions   json.RawMessage     `json:"extensions,omitempty"`
	Extras       json.RawMessage     `json:"extras,omitempty"`
}

// CameraPerspective holds perspective projection parameters.
type CameraPerspective struct {
	AspectRatio *float64        `json:"aspectRatio,omitempty"`
	YFOV        float64         `json:"yfov"`
	ZFar        *float64        `json:"zfar,omitempty"`
	ZNear       float64         `json:"znear"`
	Extensions  json.RawMessage `json:"extensions,omitempty"`
	Extras      json.RawMessage `json:"extras,omitempty"`
}

// CameraOrthographic holds orthographic projection parameters.
type CameraOrthographic struct {
	XMag       float64         `json:"xmag"`
	YMag       float64         `json:"ymag"`
	ZFar       float64         `json:"zfar"`
	ZNear      float64         `json:"znear"`
	Extensions json.RawMessage `json:"extensions,omitempty"`
	Extras     json.RawMessage `json:"extras,omitempty"`
}
